service: aws-billing-to-telegram

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  environment:
    TELEGRAM_USER: ${env:TELEGRAM_USER}
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN}
    ACCESS_KEY: ${env:ACCESS_KEY}
    SECRET_KEY: ${env:SECRET_KEY}
    CREDITS_EXPIRE_DATE: ${env:CREDITS_EXPIRE_DATE, ''}
    CREDITS_REMAINING_AS_OF: ${env:CREDITS_REMAINING_AS_OF, ''}
    CREDITS_REMAINING: ${env:CREDITS_REMAINING, ''}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ce:GetCostAndUsage'
      Resource: '*'

functions:
  report_cost:
    handler: handler.report_cost

    events:
      # Every day at 15:00 UTC / 10am CDT
      - schedule: cron(0 15 * * ? *)
