service: aws-billing-to-telegram

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.7
  region: us-east-1

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'ce:GetCostAndUsage'
      Resource: '*'

functions:
  report_cost:
    handler: handler.report_cost

    events:
      # Every day at 15:00 UTC / 10am CDT
      - schedule: cron(0 15 * * ? *)

    environment:
      TELEGRAM_USER: ${opt:telegram_user}
      TELEGRAM_BOT_TOKEN: ${opt:telegram_bot_token}
      ACCESS_KEY: ${opt:access_key}
      SECRET_KEY: ${opt:secret_key}
      CREDITS_EXPIRE_DATE: ${opt:credits_expire_date}
      CREDITS_REMAINING_AS_OF: ${opt:credits_remaining_date}
      CREDITS_REMAINING: ${opt:credits_remaining}
